name: Create Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create_release:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the workflow has write permissions to the repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Get current version
        id: get_version
        run: echo "::set-output name=version::$(jq -r .version system.json)"

      - name: Increment version
        id: increment_version
        run: |
          current_version=${{ steps.get_version.outputs.version }}
          IFS='.' read -r -a version_parts <<< "$current_version"
          version_parts[2]=$((version_parts[2] + 1))
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          echo "::set-output name=new_version::$new_version"


      - name: Create zip file
        run: zip -r cain.zip .

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: v${{ steps.increment_version.outputs.new_version }}
          name: Release ${{ steps.increment_version.outputs.new_version }}
          body: |
            ## Changes in this release
            - Automatically generated release notes.
          generateReleaseNotes: true
          artifacts: cain.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
